### PR TITLE
Starring -> staring

### PR DESCRIPTION
**Pull request by maelle**

### CODE REVIEW

**Comment by sinarueeger** [comment]
Thank you so much @maelle!
(Having a vague memory that a direct-PR button can be added to a blogdown post)

**Comment by maelle** [comment]
Yes! Here is how @apreshill added mine https://github.com/maelle/simplymaelle/pull/10 and https://github.com/maelle/simplymaelle/pull/11

**Comment by sinarueeger** [comment]
This is it! I can't copy-paste though, bc my folder structure is different (read: a labyrinth). But I love hacking, just need sometime ;-)

**Comment by sinarueeger** [comment]
I spent 1 hour on this and then gave up. 

But scrolling through the layout/partial/*htmls I found a solution that actually solves another problem I had: I wanted to add the R code of the Rmd file too. 

So now I add this to the Rmd headers: 
```
url_source: path-to-the-Rmd-file
url_code: path-to-the-R-file
```

By far not as elegant as your solution, but will do the trick till the temperatures reach a bareable level ;-)

**Comment by maelle** [comment]
If I find time would you like me to try and experiment with your layouts file?

**Comment by sinarueeger** [comment]
Of course, not gonna say no to that 😁!

**Pull request merged**
